<?php
/**
 * Fictional, read-only communication prototype records.
 *
 * Keep these records separate from production announcements and CRAD workflows.
 */
declare(strict_types=1);

function smsCommunicationDemoAnnouncements(): array
{
    return [
        [
            'id' => 'ann-1',
            'title' => 'Research proposal defense schedule released',
            'category' => 'Defense',
            'published_at' => '2026-09-28',
            'audience' => 'Research students',
            'status' => 'Published',
            'priority' => 'Important',
            'description' => 'The October proposal defense lineup is available. Please review your assigned time and panel details.',
            'author' => 'CRAD Research Office',
        ],
        [
            'id' => 'ann-2',
            'title' => 'Final manuscript submission deadline',
            'category' => 'Deadline',
            'published_at' => '2026-09-27',
            'audience' => 'Thesis groups',
            'status' => 'Published',
            'priority' => 'Important',
            'description' => 'Final manuscripts for the October defense cycle must be submitted by October 18 at 5:00 PM.',
            'author' => 'Research Coordination Desk',
        ],
        [
            'id' => 'ann-3',
            'title' => 'Research consultation hours this week',
            'category' => 'Research',
            'published_at' => '2026-09-26',
            'audience' => 'Research students',
            'status' => 'Published',
            'priority' => 'Normal',
            'description' => 'Advisers will hold consultation hours on September 30 in the Research Hub and via the campus meeting rooms.',
            'author' => 'College of Computer Studies',
        ],
        [
            'id' => 'ann-4',
            'title' => 'Panel evaluation rubric updated',
            'category' => 'Research',
            'published_at' => '2026-09-24',
            'audience' => 'Faculty & panel',
            'status' => 'Published',
            'priority' => 'Normal',
            'description' => 'The sample rubric now includes a section for research ethics and data stewardship.',
            'author' => 'CRAD Research Office',
        ],
        [
            'id' => 'ann-5',
            'title' => 'Research presentation rehearsal sign-up',
            'category' => 'General',
            'published_at' => '2026-09-22',
            'audience' => 'Research students',
            'status' => 'Draft',
            'priority' => 'Normal',
            'description' => 'A draft notice for presentation rehearsal slots in the Research Hub.',
            'author' => 'Student Research Council',
        ],
        [
            'id' => 'ann-6',
            'title' => 'September research forum recap',
            'category' => 'General',
            'published_at' => '2026-09-18',
            'audience' => 'Everyone',
            'status' => 'Archived',
            'priority' => 'Normal',
            'description' => 'Highlights and shared resources from the September research forum.',
            'author' => 'CRAD Research Office',
        ],
        [
            'id' => 'ann-7',
            'title' => 'Title submission window closes October 2',
            'category' => 'Deadline',
            'published_at' => '2026-09-29',
            'audience' => 'Research students',
            'status' => 'Published',
            'priority' => 'Urgent',
            'description' => 'Submit title packets before 5:00 PM on October 2 to be included in the current review cycle.',
            'author' => 'Research Coordination Desk',
        ],
        [
            'id' => 'ann-8',
            'title' => 'Old orientation room notice',
            'category' => 'General',
            'published_at' => '2026-09-15',
            'audience' => 'Faculty & panel',
            'status' => 'Unpublished',
            'priority' => 'Normal',
            'description' => 'Previous room assignment notice retained as an example of an unpublished record.',
            'author' => 'CRAD Research Office',
        ],
    ];
}

function smsCommunicationDemoEvents(): array
{
    return [
        [
            'id' => 'evt-1',
            'title' => 'Research Consultation',
            'type' => 'Consultation',
            'date' => '2026-09-30',
            'start_time' => '9:00 AM',
            'end_time' => '12:00 PM',
            'location' => 'Research Hub · Room 204',
            'research_group' => 'Group 2026-014 · Project SALINLAHI',
            'audience' => 'Research students',
            'status' => 'Scheduled',
            'description' => 'Adviser consultation block for groups preparing title packets and proposal chapters.',
        ],
        [
            'id' => 'evt-2',
            'title' => 'Research Title Submission Deadline',
            'type' => 'Deadline',
            'date' => '2026-10-02',
            'start_time' => '8:00 AM',
            'end_time' => '5:00 PM',
            'location' => 'CRAD Student Services Desk',
            'research_group' => 'All research groups',
            'audience' => 'Research students',
            'status' => 'Upcoming',
            'description' => 'Last day to submit a complete title packet for the October review cycle.',
        ],
        [
            'id' => 'evt-3',
            'title' => 'Research Proposal Defense',
            'type' => 'Defense',
            'date' => '2026-10-05',
            'start_time' => '9:00 AM',
            'end_time' => '12:00 PM',
            'location' => 'Research Hall · Room 301',
            'research_group' => 'Group 2026-014 · Project SALINLAHI',
            'audience' => 'Research students & panel',
            'status' => 'Scheduled',
            'description' => 'Proposal presentation and panel question period for the fictional sample group.',
        ],
        [
            'id' => 'evt-4',
            'title' => 'Panel Evaluation',
            'type' => 'Evaluation',
            'date' => '2026-10-07',
            'start_time' => '1:00 PM',
            'end_time' => '3:00 PM',
            'location' => 'Faculty Conference Room',
            'research_group' => 'Group 2026-021 · Project GABAY',
            'audience' => 'Faculty & panel',
            'status' => 'Scheduled',
            'description' => 'Panel members review the sample proposal and submit evaluation notes.',
        ],
        [
            'id' => 'evt-5',
            'title' => 'Chapter Submission Deadline',
            'type' => 'Deadline',
            'date' => '2026-10-10',
            'start_time' => '8:00 AM',
            'end_time' => '5:00 PM',
            'location' => 'Research Portal',
            'research_group' => 'All thesis groups',
            'audience' => 'Research students',
            'status' => 'Upcoming',
            'description' => 'Upload the revised chapter draft and adviser consultation notes.',
        ],
        [
            'id' => 'evt-6',
            'title' => 'Pre-Oral Defense',
            'type' => 'Defense',
            'date' => '2026-10-13',
            'start_time' => '10:00 AM',
            'end_time' => '1:00 PM',
            'location' => 'Research Hall · Room 302',
            'research_group' => 'Group 2026-021 · Project GABAY',
            'audience' => 'Research students & panel',
            'status' => 'Scheduled',
            'description' => 'Pre-oral presentation and feedback session for the fictional sample group.',
        ],
        [
            'id' => 'evt-7',
            'title' => 'Research Presentation',
            'type' => 'Presentation',
            'date' => '2026-10-15',
            'start_time' => '2:00 PM',
            'end_time' => '4:00 PM',
            'location' => 'Innovation Theater',
            'research_group' => 'Group 2026-008 · Project TALA',
            'audience' => 'Everyone',
            'status' => 'Scheduled',
            'description' => 'Short research presentation and moderated discussion for the demo cohort.',
        ],
        [
            'id' => 'evt-8',
            'title' => 'Final Defense',
            'type' => 'Defense',
            'date' => '2026-10-20',
            'start_time' => '9:00 AM',
            'end_time' => '12:00 PM',
            'location' => 'Research Hall · Room 301',
            'research_group' => 'Group 2026-008 · Project TALA',
            'audience' => 'Research students & panel',
            'status' => 'Scheduled',
            'description' => 'Final oral defense slot for a fictional capstone research group.',
        ],
        [
            'id' => 'evt-9',
            'title' => 'Final Manuscript Submission',
            'type' => 'Deadline',
            'date' => '2026-10-23',
            'start_time' => '8:00 AM',
            'end_time' => '5:00 PM',
            'location' => 'Research Portal',
            'research_group' => 'All thesis groups',
            'audience' => 'Research students',
            'status' => 'Upcoming',
            'description' => 'Final signed manuscript and repository files are due for the October cycle.',
        ],
    ];
}

function smsCommunicationDemoDateLabel(string $date, string $format = 'M j, Y'): string
{
    $parsed = DateTimeImmutable::createFromFormat('!Y-m-d', $date);
    return $parsed ? $parsed->format($format) : $date;
}
